
DECLARE @Countries TABLE(Id INT, DensoCode VARCHAR(5), SATCode VARCHAR(5), Name VARCHAR(100))

INSERT INTO @Countries
VALUES
(1, 'A0', 'ABW', 'ARUBA'),
(2, 'A1', 'AFG', 'AFGANISTAN'),
(3, 'A2', 'ALB', 'ALBANIA'),
(4, 'A4', 'DEU', 'GERMANY'),
(5, 'A6', 'BFA', 'BURKINA FASO'),
(6, 'A7', 'AND', 'ANDORRA'),
(7, 'A8', 'AGO', 'ANGOLA'),
(8, 'A9', 'ATG', 'ANTIGUA AND BARBUDA'),
(9, 'AI', 'AIA', 'ANGUILA'),
(10, 'AM', 'ARM', 'ARMENIA'),
(11, 'AZ', 'AZE', 'AZERBAIJAN'),
(12, 'B1', null, 'NETHERLANDS ANTILLAS'),
(13, 'B2', 'SAU', 'SAUDI ARABIA'),
(14, 'B3', 'DZA', 'ALGERIA'),
(15, 'B4', 'ARG', 'ARGENTINA'),
(16, 'B5', 'AUS', 'AUSTRALIA'),
(17, 'B6', 'AUT', 'AUSTRIA'),
(18, 'B7', 'BHS', 'BAHAMAS'),
(19, 'B8', null, 'BAHRAIN'),
(20, 'B9', null, 'BANGLADESH'),
(21, 'BY', null, 'BELARUS'),
(22, 'C1', null, 'BARBADOS'),
(23, 'C2', 'BEL', 'BELGIUM'),
(24, 'C3', 'BLZ', 'BELIZE'),
(25, 'C4', 'BMU', 'BERMUDA'),
(26, 'C5', null, 'UNION OF MYANMAR'),
(27, 'C6', 'BOL', 'BOLIVIA'),
(28, 'C7', null, 'BOTSWANA'),
(29, 'C8', 'BRA', 'BRAZIL'),
(30, 'C9', 'BRN', 'BRUNEI'),
(31, 'CF', null, 'CENTRAL AFRICAN REPUBLIC'),
(32, 'CZ', null, 'CZECH REPUBLIC'),
(33, 'D0', null, 'CURACAO'),
(34, 'D1', 'BGR', 'BULGARIA'),
(35, 'D2', 'BDI', 'BURUNDI'),
(36, 'D3', 'BTN', 'BUTAN'),
(37, 'D4', 'CPV', 'CAPE VERDE'),
(38, 'D6', null, 'CAYMAN ISLANDS'),
(39, 'D7', 'KHM', 'CAMBODIA'),
(40, 'D8', 'CMR', 'CAMEROON'),
(41, 'D9', 'CAN', 'CANADA'),
(42, 'E1', null, 'CHANNEL ISLANDS'),
(43, 'E2', 'CIA', 'VATICAN CITY'),
(44, 'E3', 'CCK', 'COCOS'),
(45, 'E4', 'COL', 'COLOMBIA'),
(46, 'E5', null, 'COMOROS ISLANDS'),
(47, 'E6', 'COG', 'CONGO'),
(48, 'E7', null, 'COOK ISLANDS'),
(49, 'E8', 'PRK', 'KOREA'),
(50, 'E9', 'KOR', 'KOREA'),
(51, 'EH', null, 'WESTERN SAHARA'),
(52, 'ER', null, 'ERITREA'),
(53, 'EU', null, 'EUROPEAN COMMUNITY'),
(54, 'F1', null, 'IVORY COAST'),
(55, 'F2', 'CRI', 'COSTA RICA'),
(56, 'F3', 'CUB', 'CUBA'),
(57, 'F4', 'TCD', 'CHAD'),
(58, 'F6', 'CHL', 'CHILE'),
(59, 'F7', 'TWN', 'TAIWAN'),
(60, 'F8', null, 'CYPRUS'),
(61, 'F9', null, 'BENIN'),
(62, 'FK', null, 'FALKLAND ISLANDS'),
(63, 'FM', null, 'FEDERAL STATE OF MICRONESIA'),
(64, 'G0', 'EST', 'ESTONIA'),
(65, 'G1', null, 'DENMARK'),
(66, 'G1', null, 'GIBRALTAR'),
(67, 'G2', 'DMA', 'DOMINICA'),
(68, 'G3', 'ECU', 'ECUADOR'),
(69, 'G4', 'EGY', 'EGYPT'),
(70, 'G5', 'SLV', 'EL SALVADOR'),
(71, 'G6', 'ARE', 'UNITED ARAB EMIRATES'),
(72, 'G7', 'ESP', 'SPAIN'),
(73, 'G8', 'USA', 'USA'),
(74, 'G9', 'ETH', 'ETHIOPIA'),
(75, 'GE', 'GEO', 'GEORGIA'),
(76, 'GL', 'GRL', 'GREENLAND'),
(77, 'GZ', null, 'GAZA STRIP'),
(78, 'H1', 'FJI', 'FIJI'),
(79, 'H3', 'PHL', 'PHILIPPINES'),
(80, 'H4', 'FIN', 'FINLAND'),
(81, 'H5', 'FRA', 'FRANCE'),
(82, 'H6', null, 'GABON'),
(83, 'H7', 'GMB', 'GAMBIA'),
(84, 'H8', 'GHA', 'GHANA'),
(85, 'HM', null, 'HEARD AND MCDONALDS ISLANDS'),
(86, 'HR', 'HRV', 'CROATIA'),
(87, 'I1', 'GRD', 'GRANADA'),
(88, 'I2', 'GRC', 'GREACE'),
(89, 'I4', 'GLP', 'GUADALUPE'),
(90, 'I5', 'GUM', 'GUAM'),
(91, 'I6', 'GTM', 'GUATEMALA'),
(92, 'I7', 'GUF', 'FRENCH GUYANA'),
(93, 'I8', 'GIN', 'GUINEA'),
(94, 'I9', 'GNQ', 'EQUATORIAL GUINEA'),
(95, 'J1', null, 'GUINEA-BISSAU'),
(96, 'J2', 'GUY', 'GUYANA'),
(97, 'J3', 'HTI', 'HAITI'),
(98, 'J4', 'ZYA', 'NETHERLANDS'),
(99, 'J5', 'HND', 'HONDURAS'),
(100, 'J6', 'HKG', 'HONG KONG'),
(101, 'J7', 'HUN', 'HUNGARY'),
(102, 'J8', 'IND', 'INDIA'),
(103, 'J9', 'IDN', 'INDONESIA'),
(104, 'K1', 'IRQ', 'IRAQ'),
(105, 'K2', 'IRN', 'IRAN'),
(106, 'K3', null, 'IRELAND'),
(107, 'K4', null, 'ICELAND'),
(108, 'K5', 'ISR', 'ISRAEL'),
(109, 'K6', 'ITA', 'ITALY'),
(110, 'K7', 'JAM', 'JAMAICA'),
(111, 'K9', 'JPN', 'JAPAN'),
(112, 'KG', null, 'KYRGYZSTAN'),
(113, 'KZ', 'KAZ', 'KAZAKHSTAN'),
(114, 'L0', null, 'KIRIBATI'),
(115, 'L1', 'JOR', 'JORDAN'),
(116, 'L2', 'KEN', 'KENYA'),
(117, 'L3', 'KWT', 'KUWAIT'),
(118, 'L4', null, 'LAOS PEOPLES DEMOCRATIC REP.'),
(119, 'L5', null, 'LIECHTENSTEIN'),
(120, 'L6', null, 'LESOTHO'),
(121, 'L7', null, 'LEBANON'),
(122, 'L8', 'LBR', 'LIBERIA'),
(123, 'L9', 'LBY', 'LIBYA'),
(124, 'M0', 'LUX', 'LUXEMBOURG'),
(125, 'M1', 'MAC', 'MACAO'),
(126, 'M2', 'MDG', 'MADAGASCAR'),
(127, 'M3', 'MYS', 'MALAYSIA'),
(128, 'M4', null, 'MALAWI'),
(129, 'M5', null, 'MALDIVES'),
(130, 'M6', 'MLI', 'MALI'),
(131, 'M7', 'MLT', 'MALTA'),
(132, 'M8', 'MAR', 'MOROCCO'),
(133, 'M9', 'MTQ', 'MARTINICA'),
(134, 'MD', 'MDA', 'MOLDOVA'),
(135, 'ME', null, 'MONTENEGRO'),
(136, 'MH', null, 'MARSHALL ISLANDS'),
(137, 'MK', 'MKD', 'MACEDONIA'),
(138, 'MP', null, 'NORTHERN MARIANA ISLANDS'),
(139, 'N1', null, 'REPUBLIC OF MAURITIUS'),
(140, 'N2', null, 'ISLAMIC REPUBLIC OF MAURITANIA'),
(141, 'N3', 'MEX', 'MEXICO'),
(142, 'N4', 'MNG', 'MONGOLIA'),
(143, 'N5', null, 'MONSERRAT ISLAND'),
(144, 'N6', null, 'REP. OF MOZAMBIQUE'),
(145, 'N7', null, 'NAURU'),
(146, 'N8', null, 'CHRISTMAS ISLANDS'),
(147, 'N9', 'NPL', 'NEPAL'),
(148, 'NC', null, 'NEW CALEDONIA'),
(149, 'NO', 'MCO', 'MONACO'),
(150, 'NT', null, 'NEUTRAL ZONE IRAQ-SAUDI ARABIA'),
(151, 'P0', null, 'NAMIBIA'),
(152, 'P1', 'NIC', 'NICARAGUA'),
(153, 'P2', 'NER', 'NIGER'),
(154, 'P3', 'NGA', 'NIGERIA'),
(155, 'P4', 'NIU', 'NIVE'),
(156, 'P5', null, 'NORFOLK'),
(157, 'P6', null, 'NORWAY'),
(158, 'P8', null, 'PAPUA NEW GUINEA'),
(159, 'P9', 'NZL', 'NEW ZEALAND'),
(160, 'PS', null, 'PALESTINE'),
(161, 'PW', null, 'PALAU'),
(162, 'Q1', null, 'VANUATU'),
(163, 'Q2', null, 'OMAN'),
(164, 'Q3', null, 'PACIFIC ISLAND'),
(165, 'Q7', 'PAK', 'PAKISTAN'),
(166, 'Q8', 'PAN', 'PANAMA'),
(167, 'R1', 'PRY', 'PARAGUAY'),
(168, 'R2', 'PER', 'PERU'),
(169, 'R3', null, 'PITCAIRNS'),
(170, 'R4', null, 'FRENCH POLYNESIA'),
(171, 'R5', 'POL', 'POLAND'),
(172, 'R6', 'PRT', 'PORTUGAL'),
(173, 'R7', 'PRI', 'PUERTO RICO'),
(174, 'R8', 'QAT', 'QATAR'),
(175, 'R9', 'GBR', 'UNITED KINGDOM'),
(176, 'RS', null, 'RE. OF SERBIA'),
(177, 'RU', 'RUS', 'RUSSIA'),
(178, 'S2', 'DOM', 'DOMINICAN REPUBLIC'),
(179, 'S4', null, 'ZIMBABWE'),
(180, 'S5', 'ROM', 'ROMANIA'),
(181, 'S6', null, 'RWANDAN REP.'),
(182, 'S8', 'WSM', 'SAMOA'),
(183, 'S9', null, 'SAINT KITTS AND NEVIS'),
(184, 'SB', null, 'SALOMON ISLANDS'),
(185, 'SI', null, 'SLOVENIA'),
(186, 'SJ', null, 'SVALBARD AND JAN MAYEN ISLANDS'),
(187, 'SK', null, 'SLOVAK REPUBLIC'),
(188, 'T0', 'SMR', 'SAN MARINO'),
(189, 'T1', 'SPM', 'SAN PEDRO AND MIQUELON'),
(190, 'T2', null, 'SAINT VICENT AND GRENADINES'),
(191, 'T3', 'SHN', 'SANTA ELENA'),
(192, 'T4', 'LCA', 'SANTA LUCIA'),
(193, 'T5', null, 'SAO TOME AND PRINCIPE'),
(194, 'T6', 'SEN', 'SENEGAL'),
(195, 'T7', null, 'SEYCHELLES'),
(196, 'T8', 'SLE', 'SIERRA LEONE'),
(197, 'TF', null, 'FRENCH,TERRITORIES,SOTHERN AND ANTARTIC'),
(198, 'TJ', null, 'TADJIKISTAN'),
(199, 'TK', null, 'TOKELAU ISLANDS'),
(200, 'TM', null, 'TURKMENISTAN'),
(201, 'TO', 'TON', 'TONGA'),
(202, 'TP', null, 'EAST TIMOR'),
(203, 'TV', null, 'TUVALU'),
(204, 'U1', 'SGP', 'SINGAPORE'),
(205, 'U2', 'SYR', 'SYRIA'),
(206, 'U3', 'SOM', 'SOMALIA'),
(207, 'U4', null, 'SRI LANKA'),
(208, 'U5', 'ZAF', 'SOUTH AFRICA'),
(209, 'U6', 'SDN', 'SUDAN'),
(210, 'U7', null, 'SWEDEN'),
(211, 'U8', null, 'SWITZERLAND'),
(212, 'U9', 'SUR', 'SURINAME'),
(213, 'UA', 'UKR', 'UKRAINE'),
(214, 'V0', null, 'SWAZILAND'),
(215, 'V1', 'THA', 'THAILAND'),
(216, 'V2', 'TZA', 'TANZANIA'),
(217, 'V3', null, 'BRITISH INDIAN OCEAN'),
(218, 'V4', null, 'DJIBOUTI'),
(219, 'V7', 'TGO', 'TOGO'),
(220, 'W1', 'TTO', 'TRINIDAD AND TOBAGO'),
(221, 'W2', null, 'TUNISIA'),
(222, 'W3', null, 'TURKS AND CAICOS'),
(223, 'W4', 'TUR', 'TURKEY'),
(224, 'W5', null, 'UGANDA'),
(225, 'W7', 'URY', 'URUGUAY'),
(226, 'W8', 'VEN', 'VENEZUELA'),
(227, 'W9', 'VNM', 'VIETNAM'),
(228, 'WF', null, 'WALLIS AND FUTUNA ISLANDS'),
(229, 'X2', null, 'VIRGIN ISLANDS (BRITISH)'),
(230, 'X3', null, 'VIRGIN ISLANDS (AMERICAN)'),
(231, 'X7', null, 'BOSNIA AND HERZEGOVINA'),
(232, 'X8', 'YUG', 'YUGOSLAVIA'),
(233, 'X9', null, 'REP. OF CONGO'),
(234, 'Y1', null, 'LATVIA'),
(235, 'Y2', null, 'LITHUANIA'),
(236, 'Y4', null, 'UZBEJISTAN'),
(237, 'YE', 'YEM', 'YEMEN'),
(238, 'Z1', 'ZMB', 'ZAMBIA'),
(239, 'Z2', null, 'PANAMA CANAL ZONE'),
(240, 'Z3', 'CHN', 'CHINA'),
(241, 'Z9', null, 'COUNTRIES NOT DECLARED')

INSERT INTO DensoCountries(Id, DensoCode, SatCode, Name, IsActive)
SELECT t1.Id, t1.DensoCode, t1.SATCode, t1.Name, 1
FROM @Countries t1
	LEFT OUTER JOIN DensoCountries t2 ON t2.DensoCode = t1.DensoCode
WHERE t2.Id IS NULL