import { NgModule } from '@angular/core';

import {
    DxDataGridModule,
    DxButtonModule,
    DxTextBoxModule,
    DxTagBoxModule,
    DxValidatorModule,
    DxTextAreaModule,
    DxSelectBoxModule,
    DxTabsModule,
    DxAccordionModule,
    DxTabPanelModule,
    DxFormModule,
    DxPopoverModule,
    DxListModule,
    DxHtmlEditorModule,
    DxDateBoxModule,
    DxBoxModule,
    DxDrawerModule,
    DxRadioGroupModule,
    DxPopupModule,
    DxNumberBoxModule,
    DxSwitchModule,
    DxCheckBoxModule,
    DxToastModule,
    DxDropDownButtonModule,
    DxSchedulerModule,
    DxDropDownBoxModule,
    DxTreeViewModule,
} from 'devextreme-angular';

@NgModule({
    imports: [
        DxDataGridModule,
        DxButtonModule,
        DxTextBoxModule,
        DxTagBoxModule,
        DxValidatorModule,
        DxTextAreaModule,
        DxSelectBoxModule,
        DxTabsModule,
        DxAccordionModule,
        DxTabPanelModule,
        DxFormModule,
        DxPopoverModule,
        DxListModule,
        DxHtmlEditorModule,
        DxDateBoxModule,
        DxBoxModule,
        DxDrawerModule,
        DxRadioGroupModule,
        DxPopupModule,
        DxNumberBoxModule,
        DxSwitchModule,
        DxCheckBoxModule,
        DxToastModule,
        DxDropDownButtonModule,
        DxSchedulerModule,
        DxDropDownBoxModule,
        DxTreeViewModule,
    ],
    declarations: [],
    exports: [
        DxDataGridModule,
        DxButtonModule,
        DxTextBoxModule,
        DxTagBoxModule,
        DxValidatorModule,
        DxTextAreaModule,
        DxSelectBoxModule,
        DxTabsModule,
        DxAccordionModule,
        DxTabPanelModule,
        DxFormModule,
        DxPopoverModule,
        DxListModule,
        DxHtmlEditorModule,
        DxDateBoxModule,
        DxBoxModule,
        DxDrawerModule,
        DxRadioGroupModule,
        DxPopupModule,
        DxNumberBoxModule,
        DxSwitchModule,
        DxCheckBoxModule,
        DxToastModule,
        DxDropDownButtonModule,
        DxSchedulerModule,
        DxDropDownBoxModule,
        DxTreeViewModule,
    ],
    entryComponents: [],
    providers: [],
})
export class DevExtremeSharedModule {}
